apiVersion: apps/v1
kind: Deployment
metadata:
name: project1-app
spec:
replicas: 2
selector:
matchLabels:
app: project1
template:
metadata:
labels:
app: project1
spec:
containers:- name: app
image: YOUR-DOCKERHUB/project1-cicd:latest
ports:- containerPort: 8080

--
apiVersion: v1
kind: Service
metadata:
name: project1-service
spec:
type: NodePort
selector:
app: project1
ports:- port: 8080
targetPort: 8080
nodePort: 30001
